[profile.default]
src = "."
test = "."
out = "out"
script = "script"
solc = "0.8.24"
via_ir = true
optimizer = true
optimizer_runs = 200
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false

fs_permissions = [{ access = "read", path = "script/" }]

[lint]
ignore = ["lib/**/*.sol"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[invariant]
runs = 64
depth = 48
fail_on_revert = false
